version: '3'
services:
        factory4:
                container_name: tflite_converter
                image: kotzyi/tflite_converter:0.1.0
                command: /home/tflite_converter/entrypoint.sh
                runtime: nvidia
                environment:
                        - "EXPORTED_MODEL_SAVED_PATH=${EXPORTED_MODEL_SAVED_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING="
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/model_trainer/models/exported-models:/home/tflite_converter/exported-models
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite_converter/entrypoint.sh:/home/tflite_converter/entrypoint.sh
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite_converter/scripts:/home/tflite_converter/scripts
