model:
    classifier:
        b0: &default_classifier
            NUM_CLASSES: 2
            IMAGE_SIZE: 224
            BATCH_SIZE: 64
            LEARNING_RATE: 1e-3
            EPOCHS: 10
            MODEL_NAME: b0
        b1:
            <<: *default_classifier
            IMAGE_SIZE: 240
            MODEL_NAME: b1
        b2:
            <<: *default_classifier
            IMAGE_SIZE: 260
            MODEL_NAME: b2
        b3:
            <<: *default_classifier
            IMAGE_SIZE: 300
            MODEL_NAME: b3
        b4:
            <<: *default_classifier
            IMAGE_SIZE: 380
            MODEL_NAME: b4
        b5:
            <<: *default_classifier
            IMAGE_SIZE: 456
            MODEL_NAME: b5
        b6:
            <<: *default_classifier
            IMAGE_SIZE: 528
            MODEL_NAME: b6
        b7:
            <<: *default_classifier
            IMAGE_SIZE: 600
            MODEL_NAME: b7
    detector:
        d0: &default_detector
            NUM_CLASS: 2
            IMAGE_SIZE: 512
            BATCH_SIZE: 4
            TOTAL_STEP: 100
            NUM_BOXES: 10
            REPLICAS_TO_AGGREGATE: 8
            MODEL_TYPE: detection
            WARMUP_STEP: 10
            CLASSIFICATION_WEIGHT: 1.0
            LOCALIZATION_WEIGHT: 1.0
            MODEL_NAME: efficientdet_d0_coco17_tpu-32
        d1:
            <<: *default_detector
            IMAEG_SIZE: 640
            MODEL_NAME: efficientdet_d1_coco17_tpu-32
        d2:
            <<: *default_detector
            IMAEG_SIZE: 768
            MODEL_NAME: efficientdet_d2_coco17_tpu-32
        d3:
            <<: *default_detector
            IMAEG_SIZE: 896
            MODEL_NAME: efficientdet_d3_coco17_tpu-32
        d4:
            <<: *default_detector
            IMAEG_SIZE: 1024
            MODEL_NAME: efficientdet_d4_coco17_tpu-32

kafka:
    detector:
        bootstrap_servers: 52.141.56.0:9092
        producer: &default_producer
            partition: 0
            topics: [CVT_OD_TF_MDL, REQ_CRT_CL_MDL]
        consumer: &default_consumer
            consumer_group_id: OBJECT_DETECTOR
            topics: [REQ_CVT_TF_MDL]
            consumer_timeout_ms: 5000
            sleep: 3
            max_records: 1
    classifier:
        model_type: classifier
        bootstrap_servers: 52.141.56.0:9092
        producer:
            <<: *default_producer
            topics: [CVT_CL_TF_MDL]
        consumer:
            <<: *default_consumer
            consumer_group_id: CLASSIFIER
            topics: [REQ_CRT_CL_MDL]
    converter:
        bootstrap_servers: 52.141.56.0:9092
        producer:
            <<: *default_producer
            topics: [RESP_CVT_TF_MDL]
        consumer:
            <<: *default_consumer
            consumer_group_id: TF_CONVERTER
            topics: [CVT_CL_TF_MDL, CVT_OD_TF_MDL]

docker:
    detector:
        build_context: /datadrive/jlee/projects/github.com/kotzyi/factory4/detector
        image: kotzyi/detector:latest
        command: /home/detector/workspace/entrypoint.sh
        runtime: nvidia
        environment:
            - IMAGE_PATH=/home/detector/workspace/images
            - IMAGE_LABEL_DIR=/home/detector/workspace/annotations/
            - TRAIN_IMAGE_PATH=/home/detector/workspace/images/train
            - TRAIN_IMAGE_LABEL_PATH=/home/detector/workspace/annotations/label_map.pbtxt
            - TRAIN_IMAGE_TFRECORD_PATH=/home/detector/workspace/annotations/train.record
            - TEST_IMAGE_PATH=/home/detector/workspace/images/tester
            - TEST_IMAGE_LABEL_PATH=/home/detector/workspace/annotations/label_map.pbtxt
            - TEST_IMAGE_TFRECORD_PATH=/home/detector/workspace/annotations/tester.record
            - TEST_IMAGE_RATIO=0.1
            - MODEL_PATH=/home/detector/workspace/models/trained-models
            - MODEL_PIPELINE_CONFIG_PATH=/home/detector/workspace/models/trained-models/pipeline.config
            - INPUT_TYPE=image_tensor
            - MODEL_SAVE_PATH=/home/detector/workspace/models/exported-models
            - TRAINED_CHECKPOINT_PATH=/home/detector/workspace/models/trained-models
            - AZURE_STORAGE_CONNECTION_STRING=
            - PRE_TRAINED_MODEL_PATH=/home/detector/workspace/models/pre-trained-models
        volumes:
            - /datadrive/jlee/projects/github.com/kotzyi/factory4/detector/:/home/detector/workspace/
    classifier:
        build_context: /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier
        image: kotzyi/classifier:0.1.0
        command: /home/classifier/entrypoint.sh
        runtime: nvidia
        environment:
            - MODEL_SAVE_PATH=/home/classifier/models/exported-models
            - PRE_TRAINED_MODEL_PATH=/home/classifier/models/pre-trained-models
            - TRAIN_IMAGE_DIR_PATH=/home/classifier/images/train
            - VAL_IMAGE_DIR_PATH=/home/classifier/images/val
            - IMAGE_DIR_PATH=/home/classifier/images
            - AZURE_STORAGE_CONNECTION_STRING=
        volumes:
            - /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier/:/home/classifier/
    converter:
        build_context: /datadrive/jlee/projects/github.com/kotzyi/factory4/converter
        image: kotzyi/converter:latest
        command: /home/converter/entrypoint.sh
        runtime: nvidia
        environment:
            - EXPORTED_MODEL_SAVED_PATH=/home/converter/models/exported-models/saved_model/
            - MODEL_FILE_NAME=model.tflite
            - AZURE_STORAGE_CONNECTION_STRING=
        volumes:
            - /datadrive/jlee/projects/github.com/kotzyi/factory4/converter/:/home/converter/
        model_volume_by_topic:
            CVT_CL_TF_MDL: /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier/models/exported-models:/home/converter/models/exported-models
            CVT_OD_TF_MDL: /datadrive/jlee/projects/github.com/kotzyi/factory4/detector/models/exported-models:/home/converter/models/exported-models
        model_filename_prefix_by_topic:
            CVT_CL_TF_MDL: class
            CVT_OD_TF_MDL: detect
