kafka:
    object_detector:
        bootstrap_servers: 52.141.56.0:9092
        producer: &default_producer
            partition: 0
            topic: CVT_OD_TF_MDL
            msg_format:
                - AZURE_SHARE_NAME
                - AZURE_OBJECT_IMAGE_DIR_PATH
                - AZURE_CLASS_IMAGE_DIR_PATH
                - AZURE_LABEL_DIR_PATH
                - MODEL_NUM_CLASS
                - MODEL_BATCH_SIZE
                - MODEL_NUM_STEP
                - MODEL_NUM_BOXES
                - MODEL_FILE_NAME
        consumer: &default_consumer
            consumer_group_id: OBJECT_DETECTOR
            topics: [REQ_CVT_TF_MDL]
            consumer_timeout_ms: 5000
            sleep: 3
            max_records: 1
            msg_format:
                - AZURE_SHARE_NAME
                - AZURE_IMAGE_DIR_PATH
                - AZURE_LABEL_DIR_PATH
    classifier:
        model_type: classifier
        bootstrap_servers: 52.141.56.0:9092
        producer:
            <<: *default_producer
            topic: CVT_CL_TF_MDL
        consumer:
            <<: *default_consumer
            consumer_group_id: CLASSIFIER
            topics: [REQ_CVT_TF_MDL]
            msg_format:
                - AZURE_SHARE_NAME
                - AZURE_CLASS_IMAGE_DIR_PATH
    tflite_converter:
        bootstrap_servers: 52.141.56.0:9092
        producer:
            <<: *default_producer
            topic: RESP_CVT_TF_MDL
        consumer:
            <<: *default_consumer
            consumer_group_id: TF_CONVERTER
            topics: [CVT_CL_TF_MDL, CVT_OD_TF_MDL]

docker:
    object_detector:
        build_context: /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector
        image: kotzyi/model-trainer:0.1.1
        command: /home/detector/entrypoint.sh
        runtime: nvidia
        environment:
            - NUM_CLASS=2
            - IMAGE_SIZE=384
            - BATCH_SIZE=16
            - TOTAL_STEP=10000
            - NUM_BOXES=10
            - REPLICAS_TO_AGGREGATE=8
            - MODEL_TYPE=detection
            - WARMUP_STEP=100
            - CLASSIFICATION_WEIGHT=1.0
            - LOCALIZATION_WEIGHT=1.0
            - IMAGE_LABEL_DIR=/home/detector/annotations/
            - IMAEG_PATH=/home/detector/images
            - TRAIN_IMAGE_PATH=/home/detector/images/train
            - TRAIN_IMAGE_LABEL_PATH=/home/detector/annotations/label_map.pbtxt
            - TRAIN_IMAGE_TFRECORD_PATH=/home/detector/annotations/train.record
            - TEST_IMAGE_PATH=/home/detector/images/tester
            - TEST_IMAGE_LABEL_PATH=/home/detector/annotations/label_map.pbtxt
            - TEST_IMAGE_TFRECORD_PATH=/home/detector/annotations/tester.record
            - TEST_IMAGE_RATIO=0.1 \
            - MODEL_PATH=/home/detector/models/trained-models
            - MODEL_PIPELINE_CONFIG_PATH=/home/detector/models/trained-models/pipeline.config
            - INPUT_TYPE=image_tensor
            - MODEL_SAVE_PATH=/home/detector/models/exported-models
            - TRAINED_CHECKPOINT_PATH=/home/detector/models/trained-models
            - AZURE_STORAGE_CONNECTION_STRING=
            - MODEL_NAME=efficientdet_d0_coco17_tpu-32
            - PRE_TRAINED_MODEL_PATH=/home/detector/models/pre-trained-models
        volumes:
            - /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector/:/home/detector/
    classifier:
        build_context: /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier
        image: kotzyi/classifier:0.1.0
        command: /home/classifier/entrypoint.sh
        runtime: nvidia
        environment:
            - LEARNING_RATE=1e-3
            - EPOCHS=3
            - MODEL_SAVE_PATH=/home/classifier/models/exported-models
            - PRE_TRAINED_MODEL_PATH=/home/classifier/models/pre-trained-models
            - IMAGE_DIR_PATH=/home/classifier/images
            - AZURE_STORAGE_CONNECTION_STRING=
            - MODEL_NAME=b0
            - BATCH_SIZE=64
            - NUM_CLASSES=2
        volumes:
            - /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier/:/home/classifier/
    tflite_converter:
        build_context: /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite_converter
        image: kotzyi/tflite-converter:0.1.0
        command: /home/tflite-converter/entrypoint.sh
        runtime: nvidia
        environment:
            - EXPORTED_MODEL_SAVED_PATH=/home/tflite-converter/models/exported-models/saved_model/
            - MODEL_FILE_NAME=model.tflite
            - AZURE_STORAGE_CONNECTION_STRING=
        volumes:
            - /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite-converter/:/home/tflite-converter/
        model_volume_by_topic:
            CVT_CL_TF_MDL: /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier/models/exported-models:/home/tflite-converter/models/exported-models
            CVT_OD_TF_MDL: /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector/models/exported-models:/home/tflite-converter/models/exported-models