version: '3'
services:
        factory4:
                container_name: classifier
                image: tensorflow/tensorflow:2.3.0-gpu
                command: /home/classifier/entrypoint.sh
                runtime: nvidia
                environment:
                        - "IMAGE_DIR_PATH=${IMAGE_DIR_PATH}"
                        - "MODEL_NAME=${MODEL_NAME}"
                        - "BATCH_SIZE=${BATCH_SIZE}"
                        - "NUM_CLASSES=${NUM_CLASSES}"
                        - "AZURE_SHARE_NAME=${AZURE_SHARE_NAME}"
                        - "AZURE_MODEL_DIR_PATH=${AZURE_MODEL_DIR_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}"
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier:/home/classifier
