version: '3'
services:
        factory4:
                container_name: classifier
                image: kotzyi/classifier:0.0.2
                command: /home/classifier/entrypoint.sh
                runtime: nvidia
                environment:
                        - "LEARNING_RATE=${LEARNING_RATE}"
                        - "EPOCHS=${EPOCHS}"
                        - "MODEL_SAVE_PATH=${MODEL_SAVE_PATH}"
                        - "PRE_TRAINED_MODEL_PATH=${PRE_TRAINED_MODEL_PATH}"
                        - "IMAGE_DIR_PATH=${IMAGE_DIR_PATH}"
                        - "MODEL_NAME=${MODEL_NAME}"
                        - "BATCH_SIZE=${BATCH_SIZE}"
                        - "NUM_CLASSES=${NUM_CLASSES}"
                        - "AZURE_SHARE_NAME=${AZURE_SHARE_NAME}"
                        - "AZURE_MODEL_DIR_PATH=${AZURE_MODEL_DIR_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}"
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier/:/home/classifier/
                        - /datadrive/jlee/images:/home/classifier/images
                working_dir: /home/classifier/