version: '3.1'
services:
        factory4:
                container_name: tflite-converter
                image: kotzyi/tflite-converter:0.1.0
                command: /home/tflite-converter/entrypoint.sh
                runtime: nvidia
                environment:
                        - "EXPORTED_MODEL_SAVED_PATH=${EXPORTED_MODEL_SAVED_PATH}"
                        - "MODEL_FILE_NAME=${MODEL_FILE_NAME}"
                        - "AZURE_SHARE_NAME=${AZURE_SHARE_NAME}"
                        - "AZURE_MODEL_DIR_PATH=${AZURE_MODEL_DIR_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}"
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier/models/exported-models:/home/tflite-converter/exported-models
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite-converter/entrypoint.sh:/home/tflite-converter/entrypoint.sh
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite-converter/scripts:/home/tflite-converter/scripts
volumes:
  models:
    external:
      name: code-${VER}