version: '3'
services:
        factory4:
                container_name: tflite-converter
                build:
                        context: ./
                        dockerfile: Dockerfile
                command: /home/tflite-converter/entrypoint.sh
                runtime: nvidia
                environment:
                        - "BLOB_MODEL_UPLOAD_PATH=${BLOB_MODEL_UPLOAD_PATH}"
                        - "EXPORTED_MODEL_SAVED_PATH=${EXPORTED_MODEL_SAVED_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING"
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/object-detector/models/exported-models:/home/tflite-converter/exported-models
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite-converter/entrypoint.sh:/home/tflite-converter/entrypoint.sh
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/tflite-converter/scripts:/home/tflite-converter/scripts
