version: '3.1'
services:
        factory4:
                container_name: converter
                image: crfactory4krcenter.azurecr.io/converter:latest
                command: /home/converter/entrypoint.sh
                runtime: nvidia
                environment:
                        - "EXPORTED_MODEL_SAVED_PATH=${EXPORTED_MODEL_SAVED_PATH}"
                        - "MODEL_FILE_NAME=${MODEL_FILE_NAME}"
                        - "AZURE_SHARE_NAME=${AZURE_SHARE_NAME}"
                        - "AZURE_MODEL_DIR_PATH=${AZURE_MODEL_DIR_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}"
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/classifier/models/exported-models:/home/converter/exported-models
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/converter:/home/converter
