version: '3'
services:
        factory4:
                container_name: detector
                image: kotzyi/detector:latest
                command: /home/detector/workspace/entrypoint.sh
                runtime: nvidia
                environment:
                        - "NUM_CLASS=${NUM_CLASS}"
                        - "IMAGE_SIZE=${IMAGE_SIZE}"
                        - "BATCH_SIZE=${BATCH_SIZE}"
                        - "TOTAL_STEP=${TOTAL_STEP}"
                        - "NUM_BOXES=${NUM_BOXES}"
                        - "REPLICAS_TO_AGGREGATE=${REPLICAS_TO_AGGREGATE}"
                        - "MODEL_TYPE=${MODEL_TYPE}"
                        - "WARMUP_STEP=${WARMUP_STEP}"
                        - "CLASSIFICATION_WEIGHT=${CLASSIFICATION_WEIGHT}"
                        - "LOCALIZATION_WEIGHT=${LOCALIZATION_WEIGHT}"
                        - "IMAGE_PATH=${IMAGE_PATH}"
                        - "IMAGE_LABEL_DIR=${IMAGE_LABEL_DIR}"
                        - "TRAIN_IMAGE_PATH=${TRAIN_IMAGE_PATH}"
                        - "TRAIN_IMAGE_LABEL_PATH=${TRAIN_IMAGE_LABEL_PATH}"
                        - "TRAIN_IMAGE_TFRECORD_PATH=${TRAIN_IMAGE_TFRECORD_PATH}"
                        - "TEST_IMAGE_PATH=${TEST_IMAGE_PATH}"
                        - "TEST_IMAGE_LABEL_PATH=${TEST_IMAGE_LABEL_PATH}"
                        - "TEST_IMAGE_TFRECORD_PATH=${TEST_IMAGE_TFRECORD_PATH}"
                        - "TEST_IMAGE_RATIO=${TEST_IMAGE_RATIO}"
                        - "MODEL_PATH=${MODEL_PATH}"
                        - "MODEL_PIPELINE_CONFIG_PATH=${MODEL_PIPELINE_CONFIG_PATH}"
                        - "INPUT_TYPE=${INPUT_TYPE}"
                        - "TRAINED_CHECKPOINT_PATH=${TRAINED_CHECKPOINT_PATH}"
                        - "MODEL_SAVE_PATH=${MODEL_SAVE_PATH}"
                        - "PRE_TRAINED_MODEL_PATH=${PRE_TRAINED_MODEL_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}"
                        - "MODEL_NAME=${MODEL_NAME}"
                        - "AZURE_SHARE_NAME=${AZURE_SHARE_NAME}"
                        - "AZURE_OBJECT_IMAGE_DIR_PATH=${AZURE_OBJECT_IMAGE_DIR_PATH}"
                        - "AZURE_LABEL_DIR_PATH=${AZURE_LABEL_DIR_PATH}"
                        - "AZURE_MODEL_DIR_PATH=${AZURE_MODEL_DIR_PATH}"
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/detector/:/home/detector/workspace/
                ports:
                        - "60066:60066"
