version: '3'
services:
        factory4:
                container_name: object_detector
                image: kotzyi/factory4:0.1.0
                command: /home/detector/entrypoint.sh
                runtime: nvidia
                environment:
                        - "TRAIN_IMAGE_PATH=${TRAIN_IMAGE_PATH}"
                        - "TRAIN_IMAGE_LABEL_PATH=${TRAIN_IMAGE_LABEL_PATH}"
                        - "TRAIN_IMAGE_TFRECORD_PATH=${TRAIN_IMAGE_TFRECORD_PATH}"
                        - "TEST_IMAGE_PATH=${TEST_IMAGE_PATH}"
                        - "TEST_IMAGE_LABEL_PATH=${TEST_IMAGE_LABEL_PATH}"
                        - "TEST_IMAGE_TFRECORD_PATH=${TEST_IMAGE_TFRECORD_PATH}"
                        - "MODEL_PATH=${MODEL_PATH}"
                        - "MODEL_PIPELINE_CONFIG_PATH=${MODEL_PIPELINE_CONFIG_PATH}"
                        - "INPUT_TYPE=${INPUT_TYPE}"
                        - "TRAINED_CHECKPOINT_PATH=${TRAINED_CHECKPOINT_PATH}"
                        - "MODEL_OUTPUT_PATH=${MODEL_OUTPUT_PATH}"
                        - "PRE_TRAINED_MODEL_PATH=${PRE_TRAINED_MODEL_PATH}"
                        - "AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}"
                        - "MODEL_NAME=${MODEL_NAME}"
                volumes:
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector/images:/home/detector/workspace/images
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector/annotations/:/home/detector/workspace/annotations
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector/models/pre-trained-models:/home/detector/workspace/models/pre-trained-models
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector/entrypoint.sh:/home/detector/entrypoint.sh
                        - /datadrive/jlee/projects/github.com/kotzyi/factory4/object_detector/scripts:/home/detector/scripts
